version: '3'

services:

  jenkins-container:
    build: .
    # no image:
    privileged: true
    restart: always
    user: root
    ports:
      - "8080:8080"
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  registry:
    image: registry
    container_name: registry
    restart: always
    ports:
      - "5001:5000"